export enum ApplicationType {
  FRONTEND_ONLY = "FRONTEND_ONLY",
  FULL_STACK = "FULL_STACK",
  API_ONLY = "API_ONLY",
  BACKGROUND_SERVICE = "BACKGROUND_SERVICE",
  DATASCIENCE_ALGORITHM = "DATASCIENCE_ALGORITHM",
  DATABASE = "DATABASE",
  LIBRARY = "LIBRARY",
  ETL = "ETL",
  SAAS = "SAAS"
}